#!/usr/bin/env python

import re
import sys
from rapidctl.cli.main import main
from rapidctl.bootstrap import client

# Create client instance
client = client.CtlClient()

# Define details about the client here.
client.container_repo = "ghcr.io/dalethestirling/rapidctl-container"
client.baseline_version = "1771729391"
client.client_version = "0.0.1"

# Lets be a cli tool. 
if __name__ == '__main__':
    try:
        client.connect()
    except Exception as e:
        print(f"Failed to connect to Podman: {e}")
        sys.exit(1)

    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main(client))
